### ISSUE TITLE
Deeper integration of CanCan into ActiveAdmin

### ISSUE THREAD

**Issue by jpmckinney** [11factory/activeadmin-cancan#3]
See my gist: https://gist.github.com/3040303

It enforces cancan on menus, action items, `default_actions` in index tables, and when using AA's `auto_link`.

**Comment by 11factory** [comment]
Thks for your job,

can you do a pull request please ?

2012/7/3 James McKinney <
reply@reply.github.com

**Comment by jpmckinney** [comment]
There are some issues expressed in the comments to that gist about the initializer raising exceptions on the legacy Dashboard and on Comments controllers, so a few tweaks need to be made.

Also, I'm not sure how you'd like to split up the gist into different files, and since the gist is longer than your entire gem, I figure you can do some copy-paste to add this useful functionality.

I'm quite happy using my initializer and skipping activeadmin-cancan altogether.

**Comment by marcusg** [comment]
hey, the gist is working well. are there any plans to integrate it inside your gem?

**Comment by jpmckinney** [comment]
No plans currently.

**Comment by marcusg** [comment]
it looks like there is no need for this gem anymore. with activeadmin 0.6.0 you can define cacan as an authorization-adapter http://activeadmin.info/docs/13-authorization-adapter.html#setting_up_your_own_authorizationadapter
