### ISSUE TITLE
Authorization Not Performed

### ISSUE THREAD

**Issue by abacha** [11factory/activeadmin-cancan#4]
I`ve installed the activeadmin gem and also this one and I'm getting this error:

```
CanCan::AuthorizationNotPerformed in Admin::DashboardController#index

This action failed the check_authorization because it does not authorize_resource. Add skip_authorization_check to bypass this check.
```

**Comment by 11factory** [comment]
Have you configured your application controller class to handle authorization errors as mentioned in project page ?
Can you show me you ability class ?
