### ISSUE TITLE
immediately after bundle install

### ISSUE THREAD

**Issue by okliv** [11factory/activeadmin-cancan#5]
/gems/activeadmin-cancan-0.1.2/lib/activeadmin-cancan/authorization.rb:9:in `register': undefined local variable or method`resource_dsl' for #ActiveAdmin::Namespace:0x007f8d41431888 (NameError)

**Comment by 11factory** [comment]
Which version of activeadmin are you using ?

**Comment by okliv** [comment]
edge one

**Comment by sheerun** [comment]
I have the same issue.

**Comment by danil-z** [comment]
i have same issue too

**Comment by Bastes** [comment]
Same here.

**Comment by 11factory** [comment]
fixed on v0.1.3

**Comment by selivandex** [comment]
the same issue

**Comment by selivandex** [comment]
right now, version 0.1.4
